#!/bin/bash
#set -x

usage() {
    cat <<EOF
$0 [options] PROG [args]"

options:    -h Show this help message
EOF
}

output() {
    local prefix=$1
    local func=$2
    local indent=$3

    printf "%s" "$prefix"
    for i in $(seq 1 $indent); do
        printf "|  "
    done
    printf "$func\n"
}

process_file() {
    local file=$1
    local pattern="^#"
    local pattern2="(.*)probe_\w+:(.*)"
    local indent=0

    while read line
    do
        if [[ $line =~ $pattern ]]; then
            continue
        fi

        if [[ $line =~ $pattern2 ]]; then
            local prefix=${BASH_REMATCH[1]}
            local func=${BASH_REMATCH[2]}

            if [[ $line =~ "_return:" ]]; then
                indent=$((indent - 1))
            else
                output "$prefix" "$func" $indent
                indent=$((indent + 1))
            fi
        fi
    done < $file
}

while getopts "h" opt; do
    case $opt in
        h)
            usage
            exit 0
            ;;
    esac
done

shift $((OPTIND -1))

if [[ $(whoami) != "root" ]]; then
    echo "Run with root privilege"
    exit 1;
fi

BIN=$(which $1)
CAPTURE=$(tempfile)
BASE=$(basename $BIN)

FUNCTIONS=$(perf probe -x $BIN -F|grep -v "@")
PROBES_LIST=$(perf probe -l)

echo "Adding probes..."

for func in $FUNCTIONS; do
    if [[ $PROBES_LIST =~ ":$func" ]]; then
        echo "$func is already probed"
    else
        echo "add new probe for $func"
        perf probe -x $BIN "$func=$func" > /dev/null
        perf probe -x $BIN "${func}_return=$func%return" > /dev/null
    fi
done

echo "Recoding..."
perf record -e "probe_$BASE:*" -aR $@

echo "Processing result..."
perf script > $CAPTURE

process_file $CAPTURE > tracy.txt

echo "Removing probes..."
perf probe --del "probe_$BASE:*"

rm $CAPTURE
rm perf.data

echo "Done"
