#!/bin/bash
#set -x

usage() {
    cat <<EOF
$0 [options] PROG [args]"

options:    -h Show this help message
            -v Be more verbose
EOF
}

output() {
    local prefix=$1
    local func=$2
    local indent=$3

    printf "%s" "$prefix"
    for i in $(seq 1 $indent); do
        printf "|  "
    done
    printf "$func\n"
}

process_file() {
    local file=$1
    local pattern="^#"
    local pattern2="(.*)probe_\w+:(.*)"
    local indent=0

    while read line
    do
        if [[ $line =~ $pattern ]]; then
            continue
        fi

        if [[ $line =~ $pattern2 ]]; then
            local prefix=${BASH_REMATCH[1]}
            local func=${BASH_REMATCH[2]}

            if [[ $line =~ "_return:" ]]; then
                indent=$((indent - 1))
            else
                output "$prefix" "$func" $indent
                indent=$((indent + 1))
            fi
        fi
    done < $file
}

tracy_echo() {
    if [[ $VERBOSE == 1 ]]; then
        echo "$@"
    fi
}

while getopts "hv" opt; do
    case $opt in
        h)
            usage
            exit 0
            ;;
        v)
            VERBOSE=1
            ;;
    esac
done

shift $((OPTIND -1))

if [[ $(whoami) != "root" ]]; then
    echo "Run with root privilege"
    exit 1;
fi

set -e
BIN=$(which $1)
CAPTURE=$(tempfile)
BASE=$(basename $BIN)

FUNCTIONS=$(perf probe -x $BIN -F|grep -v "@")
PROBES_LIST=$(perf probe -l)

echo "Running..."
tracy_echo "Adding probes..."

for func in $FUNCTIONS; do
    if [[ $PROBES_LIST =~ ":$func" ]]; then
        tracy_echo "$func is already probed"
    else
        tracy_echo "add new probe for $func"
        perf probe -x $BIN "$func=$func" > /dev/null
        perf probe -x $BIN "${func}_return=$func%return" > /dev/null
    fi
done

tracy_echo "Recoding..."
if [[ VERBOSE == 1 ]]; then
    perf record -e "probe_$BASE:*" -aR $@
else
    perf record -q -e "probe_$BASE:*" -aR $@
fi

tracy_echo "Processing result..."
perf script > $CAPTURE

process_file $CAPTURE > tracy.txt

tracy_echo "Removing probes..."
if [[ VERBOSE == 1 ]]; then
    perf probe --del "probe_$BASE:*"
else
    perf probe --del "probe_$BASE:*" > /dev/null
fi

rm $CAPTURE
rm perf.data

echo "Done"
